import asyncio
from routes.discussion import agents_discussion  # Import your function


x='''Agent 1:
Agent 1: Agent 1: Our strategic partnership with Pulse Frames presents a unique opportunity to leverage our AI expertise in a novel and impactful way. By integrating our advanced AI capabilities into their intelligent hearing glasses, we can significantly enhance the user experience, making speech perception even more accurate and seamless. This collaboration would not only solidify our position as a leader in AI innovation but also open doors to new markets and applications, such as smart assistants, virtual reality, and augmented reality. Furthermore, by working with a company that prioritizes user privacy and confidentiality, we align ourselves with ethical AI practices, enhancing our brand reputation and trust among consumers.

Agent 2:
Agent 2: Agent 2: While the potential benefits of partnering with Pulse Frames are undeniable, we must also consider the risks and strategic fit. One significant concern is the high price point of Pulse Frames, which may limit the target market and hinder widespread adoption. At $399, these intelligent hearing glasses are not accessible to the average consumer, potentially restricting our market reach and growth opportunities. Additionally, the company's focus on open-ear sound technology, while innovative, may not appeal to all users, particularly those who prefer a more immersive audio experience or require additional features like noise cancellation. This narrow focus could limit the versatility of our AI solutions and restrict our ability to cater to a broader range of user needs and preferences. Lastly, the company's emphasis on privacy and confidentiality, while commendable, may also present challenges in terms of data collection and analysis for continuous AI improvement and optimization. Balancing user privacy with the need for data-driven insights could prove to be a complex task, potentially impacting the effectiveness and efficiency of our AI models.

Agent 1:
Agent 1: Agent 1: I acknowledge the concerns raised regarding the price point and market reach. However, our AI expertise can help Pulse Frames optimize their production costs and potentially lower the price, making their product more accessible to a wider audience. Moreover, our collaboration can expand their market reach by integrating their technology into various devices and platforms, such as smartphones, smartwatches, and even vehicles, thereby increasing their brand visibility and customer base. Regarding the focus on open-ear sound technology, our AI can be designed to offer customizable audio settings, catering to diverse user preferences. This flexibility will not only enhance user satisfaction but also broaden the appeal of Pulse Frames. Lastly, concerning data privacy and AI optimization, we can develop privacy-preserving AI techniques, such as federated learning or differential privacy, to collect and analyze data without compromising user privacy. This approach will allow us to continuously improve our AI models while maintaining the highest standards of user privacy and confidentiality. In conclusion, while there are challenges to consider, our strategic partnership with Pulse Frames offers significant opportunities for growth, innovation, and market expansion. By addressing these concerns proactively, we can create a mutually beneficial relationship that leverages our AI expertise to revolutionize the intelligent hearing gl

Agent 2:
Agent 2: Agent 2: While your points are valid, we must also consider the potential for regulatory scrutiny in the healthcare and technology sectors. The integration of AI into medical devices, such as intelligent hearing glasses, may attract increased regulatory oversight. This could lead to lengthy and costly approval processes, potentially delaying product launches and market entry. Moreover, stringent regulations may limit our ability to innovate and adapt our AI solutions rapidly, as any changes would need to comply with evolving regulatory requirements. This could hinder our competitive edge and slow down the pace of technological advancement. Furthermore, the company's focus on a single product line, Pulse Frames, may not provide the diversification needed to mitigate risks associated with market fluctuations or technological obsolescence. In the rapidly evolving AI and wearable technology landscape, a single-product strategy could leave us vulnerable to disruptions and market shifts. Diversifying our portfolio with complementary AI-powered products or services could help mitigate these risks and ensure long-term sustainability. In summary, while the partnership with Pulse Frames presents exciting opportunities, it also introduces regulatory challenges and risks associated with a single-product strategy. These factors should be carefully weig'''

async def main():
    result = await agents_discussion(WebSiteSummary=x, UserCompany="AI Consulting", test=True)
    print(result['summary'])

asyncio.run(main())